erDiagram

    Fakt {
        int fk_1 FK
        int fk_2 FK
        type kennwert_1
        type kennwert_2
    }

    Dimension_1 {
        int pk_1 PK
        int fk_1_1 FK
        int fk_1_2 FK
        type attribut_1_1
        type attribut_1_2
    }

    Dimension_1_1 {
        int pk_1_1 PK
        type attribut_1_1_1
        type attribut_1_1_2
    }

    Dimension_1_2 {
        int pk_1_2 PK
        type attribut_1_2_1
        type attribut_1_2_2
    }

    Dimension_2 {
        int pk_2 PK
        int fk_2_1 FK
        type attribut_2_1
        type attribut_2_2
    }

    Dimension_2_1 {
        int pk_2_1 PK
        type attribut_2_1_1
        type attribut_2_1_2
    }

    Fakt }o--|| Dimension_1: " "
    Fakt }o--|| Dimension_2: " "

    Dimension_1 }o--|| Dimension_1_1: " "
    Dimension_1 }o--|| Dimension_1_2: " "
    
    Dimension_2 }o--|| Dimension_2_1: " "