erDiagram

    Dim_Produkt {
        int pk_1 PK
        string Kategorie
        string Name
    }

    Dim_Ort {
        int pk_2 PK
        string Land
        string Bundesland
        string Stadt
    }
    
    Dim_Zeit {
        int pk_3 PK
        int Jahr
        int Quartal
        int Monat
        int Tag
    }