erDiagram

    Dimension_1 {
        int pk_1 PK
        type attribut_1_1
        type attribut_1_2
        type attribut_1_3
    }

    Dimension_2 {
        int pk_2 PK
        type attribut_2_1
        type attribut_2_2
        type attribut_2_3
    }
    
    Dimension_3 {
        int pk_3 PK
        type attribut_3_1
        type attribut_3_2
        type attribut_3_3
    }